#!/bin/bash
IMG=$1
if [ -f "$IMG" ]
then
	openocd -f /usr/share/openocd/scripts/interface/stlink-v2.cfg -f /usr/share/openocd/scripts/target/stm32f0x.cfg -c init -c "reset halt" -c "flash write_image erase $1 0x08000000" -c "verify_image $1 0x08000000" -c "reset run" -c shutdown
else
	echo "Provide image file"
	exit 1
fi


